/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.29
 * Generated at: 2019-12-20 15:10:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Admin_005fpage_005fmain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv =\"Content-Type\" content=\"text/html ; charset=EUC-KR\">\r\n");
      out.write("<title>Library Administer page</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<h1>도서 대여 관리 기능</h1>\r\n");
      out.write("<hr><hr>\r\n");
      out.write("<h2>도서 추가 </h2>\r\n");
      out.write("<hr>\r\n");
      out.write("\t<form method=\"post\" action = \"Admin_page_bookInsertion.jsp\">\r\n");
      out.write("\t\t책이름: <input type=\"text\" name=\"title\" maxlength=\"40\"><br/>  \r\n");
      out.write("\t\t작가\t: <input type=\"text\" name=\"author\" maxlength=\"40\"><br/>\r\n");
      out.write("\t\t출판\t: <input type=\"text\" name=\"publisher\" maxlength=\"40\"><br/>\r\n");
      out.write("\t\t<input type=\"submit\" value=\"입력완료\">\r\n");
      out.write("\t</form>\r\n");
      out.write("<br><br>\r\n");
      out.write("\r\n");
      out.write("<h2>장서 목록 검색</h2>\r\n");
      out.write("<hr>\r\n");
      out.write("\t<form method=\"post\" action = \"Admin_page_bookSearch.jsp\">\r\n");
      out.write("\t\tSEARCH BY [<input type=\"radio\" name=\"searchBy\" value=\"ISBN\" checked>ISBN /\r\n");
      out.write("\t\t\t\t   <input type=\"radio\" name=\"searchBy\" value=\"Title\">Title ]<br/>\r\n");
      out.write("\t\t<input type = \"text\" name=\"searchVal\" maxlength = \"40\"><input type=\"submit\" value=\"검색\">\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<br>(아무것도 입력하지 않으면 전체 조회)\r\n");
      out.write("<br><br>\r\n");
      out.write("\r\n");
      out.write("<h2>대여 중인 도서 관리</h2>\r\n");
      out.write("<hr>\r\n");
      out.write("\t<form method=\"post\" action = \"Admin_page_rentDataSearch.jsp\">\r\n");
      out.write("\t\tSEARCH BY [<input type=\"radio\" name=\"searchBy\" value=\"ISBN\" checked>ISBN /\r\n");
      out.write("\t\t\t\t   <input type=\"radio\" name=\"searchBy\" value=\"Title\">Title /\r\n");
      out.write("\t\t\t\t   <input type=\"radio\" name=\"searchBy\" value=\"usrID\">userID ]<br/>\r\n");
      out.write("\t\t<input type = \"text\" name=\"searchVal\" maxlength = \"40\"><input type=\"submit\" value=\"검색\">\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<br>(아무것도 입력하지 않으면 전체 조회)\r\n");
      out.write("<br><br>\r\n");
      out.write("\r\n");
      out.write("<h2>도서 예약 정보 관리</h2>\r\n");
      out.write("<hr>\r\n");
      out.write("\t<form method=\"post\" action = \"Admin_page_reservationSearch.jsp\">\r\n");
      out.write("\t\tSEARCH BY [<input type=\"radio\" name=\"searchBy\" value=\"ISBN\" checked>ISBN /\r\n");
      out.write("\t\t\t\t   <input type=\"radio\" name=\"searchBy\" value=\"usrID\">userID ]<br/>\r\n");
      out.write("\t\t<input type = \"text\" name=\"searchVal\" maxlength = \"40\"><input type=\"submit\" value=\"검색\">\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<br>(아무것도 입력하지 않으면 전체 조회)\r\n");
      out.write("<br><br>\r\n");
      out.write("\r\n");
      out.write("<h2>반납 신청 도서 조회</h2>\r\n");
      out.write("<hr>\r\n");
      out.write("\t<form method=\"post\" action = \"Admin_page_turnInSearch.jsp\">\r\n");
      out.write("\t\tSEARCH BY [<input type=\"radio\" name=\"searchBy\" value=\"ISBN\" checked>ISBN /\r\n");
      out.write("\t\t\t\t   <input type=\"radio\" name=\"searchBy\" value=\"usrID\">userID ]<br/>\r\n");
      out.write("\t\t<input type = \"text\" name=\"searchVal\" maxlength = \"40\"><input type=\"submit\" value=\"검색\">\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<br>(아무것도 입력하지 않으면 전체 조회)\r\n");
      out.write("<br><br>\r\n");
      out.write("<h2>과거 대여 내역</h2>\r\n");
      out.write("<hr>\r\n");
      out.write("\t<form method=\"post\" action = \"Admin_page_rentalRecordSearch.jsp\">\r\n");
      out.write("\t\tFROM <input type=\"date\" name=\"date_start\" placeholder = \"YYYY-MM-DD\"> \r\n");
      out.write("\t\tTO   <input type=\"date\" name=\"date_end\" placeholder = \"YYYY-MM-DD\"> <br>\r\n");
      out.write("\t\tSEARCH BY [<input type=\"radio\" name=\"searchBy\" value=\"ISBN\" checked>ISBN /\r\n");
      out.write("\t\t\t\t   <input type=\"radio\" name=\"searchBy\" value=\"usrID\">userID ]<br/>\r\n");
      out.write("\t\t<input type = \"text\" name=\"searchVal\" maxlength = \"40\"><input type=\"submit\" value=\"검색\">\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<br>(아무것도 입력하지 않으면 전체 조회)\r\n");
      out.write("<br><br>\r\n");
      out.write("<hr><hr>\r\n");
      out.write("<h1>회원 정보 관리 기능</h1>\r\n");
      out.write("<hr><hr>\r\n");
      out.write("\t<form method=\"post\" action = \"Admin_page_searchMemberData.jsp\">\r\n");
      out.write("\t\tSEARCH BY<br/> \r\n");
      out.write("\t\t[<input type=\"radio\" name=\"searchBy\" value=\"ID\" checked> ID /\r\n");
      out.write("\t     <input type=\"radio\" name=\"searchBy\" value=\"Name\"> NAME /\r\n");
      out.write("\t     <input type=\"radio\" name=\"searchBy\" value=\"Phone\"> Phone('-'포함) /\r\n");
      out.write("\t     <input type=\"radio\" name=\"searchBy\" value=\"Email\"> Email ]<br/>\r\n");
      out.write("\t    [<input type=\"checkbox\" name=\"check_student\" value=\"student\" checked>Student\r\n");
      out.write("\t     <input type=\"checkbox\" name=\"check_graduated\" value=\"graduated\" checked>Graduated\r\n");
      out.write("\t     <input type=\"checkbox\" name=\"check_faculty_member\" value=\"faculty_member\" checked>faculty_member ]<br> \r\n");
      out.write("\t\t<input type = \"text\" name=\"searchVal\" maxlength = \"40\" > <input type=\"submit\" value=\"검색\">\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<br> (아무것도 입력 하지 않으면 전체 회원을 조회합니다.)\r\n");
      out.write("<hr>\r\n");
      out.write("<button onclick=\"location.href='Admin_page_showTopTen.jsp'\"><h2>[미구현] 최다 대출 TOP 유저 조회</h2>></button>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
