/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.29
 * Generated at: 2019-12-23 01:40:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import needs.User;

public final class Homepage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("needs.User");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	User user = (User) session.getAttribute("user");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>homepage</title>\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("       #background{\r\n");
      out.write("        background: #cccccc;\r\n");
      out.write("        height: 1000px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #title{\r\n");
      out.write("        background: black;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #mypage{\r\n");
      out.write("        background: green;\r\n");
      out.write("        border: 1px white;\r\n");
      out.write("        height: 150px;\r\n");
      out.write("        width: 150px;\r\n");
      out.write("        font-size: large;\r\n");
      out.write("        color: white;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("    #deletemypage{\r\n");
      out.write("        background: red;\r\n");
      out.write("        border: 1px white;\r\n");
      out.write("        height: 150px;\r\n");
      out.write("        width: 150px;\r\n");
      out.write("        font-size: large;\r\n");
      out.write("        color: white;\r\n");
      out.write("    }\r\n");
      out.write("    #search{\r\n");
      out.write("        background: green;\r\n");
      out.write("        border: 1px white;\r\n");
      out.write("        height: 300px;\r\n");
      out.write("        width: 300px;\r\n");
      out.write("        font-size: large;\r\n");
      out.write("        color: white;\r\n");
      out.write("    }\r\n");
      out.write("    #rental{\r\n");
      out.write("        background: blue;\r\n");
      out.write("        border: 1px white;\r\n");
      out.write("        height: 300px;\r\n");
      out.write("        width: 300px;\r\n");
      out.write("        font-size: large;\r\n");
      out.write("        color: white;\r\n");
      out.write("    }\r\n");
      out.write("    #AddBook{\r\n");
      out.write("        background: black;\r\n");
      out.write("        border: 1px white;\r\n");
      out.write("        height: 300px;\r\n");
      out.write("        width: 300px;\r\n");
      out.write("        font-size: large;\r\n");
      out.write("        color: white;\r\n");
      out.write("    }\r\n");
      out.write("    #reservation{\r\n");
      out.write("        background: violet;\r\n");
      out.write("        border: 1px white;\r\n");
      out.write("        height: 300px;\r\n");
      out.write("        width: 300px;\r\n");
      out.write("        font-size: large;\r\n");
      out.write("        color: white;\r\n");
      out.write("    }\r\n");
      out.write("    #ranking{\r\n");
      out.write("        background: rgb(211, 102, 14);\r\n");
      out.write("        border: 1px white;\r\n");
      out.write("        height: 300px;\r\n");
      out.write("        width: 300px;\r\n");
      out.write("        font-size: large;\r\n");
      out.write("        color: white;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("   <div id = \"background\">\r\n");
      out.write("\r\n");
      out.write("                <center>\r\n");
      out.write("                    <div id = \"container\">        \r\n");
      out.write("                        <div id=\"title\"><font size=\"10\" color=\"white\"><strong>도서예약관리</strong></font></br>\r\n");
      out.write("\r\n");
      out.write("                        <form method=\"post\" action=\"logout.jsp\">\r\n");
      out.write("                        <input type=\"submit\" value=\"로그아웃\"></br>\r\n");
      out.write("                        </form>\r\n");
      out.write("                        \r\n");
      out.write("                        <div><font color=\"white\">");
      out.print((String)session.getAttribute("Memstat") );
      out.write("</font></div>\r\n");
      out.write("                        <div><font color=\"white\">");
      out.print( (user == null) ? "로그인을 하십시오." : user.id );
      out.write("</font></div>\r\n");
      out.write("                        \r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <form method=\"post\" action=\"accountrestore.jsp\">\r\n");
      out.write("                    <input type=\"submit\" value=\"회원수정\" id=\"mypage\">\r\n");
      out.write("                    </form>\r\n");
      out.write("                 \t<form method=\"post\" action=\"deleteAccount.jsp\">\r\n");
      out.write("                 \t\t<input type=\"submit\" value=\"회원탈퇴\" id=\"deletemypage\">\r\n");
      out.write("                 \t</form>\r\n");
      out.write("                 \t<form method=\"post\" action=\"booksearch.jsp\">\r\n");
      out.write("                    <input type=\"submit\" value=\"도서검색\" id=\"search\">                 \r\n");
      out.write("                 \t</form>\r\n");
      out.write("                 \t\r\n");
      out.write("                    <input type=\"submit\" value=\"도서대출반납\" id=\"rental\"></br>\r\n");
      out.write("                    \r\n");
      out.write("                    <form method=\"post\" action=\"Admin_page_main.jsp\">\r\n");
      out.write("                    <input type=\"submit\" value=\"도서등록\" id=\"AddBook\">\r\n");
      out.write("                    </form>>\r\n");
      out.write("                    \r\n");
      out.write("                    <form method=\"post\" action=\"yourReservationPage.jsp\">\r\n");
      out.write("                    <input type=\"submit\" value=\"도서예약\" id=\"reservation\">\r\n");
      out.write("                    </form>\r\n");
      out.write("                    \r\n");
      out.write("                    <form method=\"post\" action=\"rankPage.jsp\">\r\n");
      out.write("                    <input type=\"submit\" value=\"랭킹 top10\" id=\"ranking\">\r\n");
      out.write("                    </form>\r\n");
      out.write("                  \t\r\n");
      out.write("                  \t<form method=\"post\" action=\"yourRentalPage.jsp\">\r\n");
      out.write("                   \t<input type=\"submit\" value=\"도서대여\" id=\"rental\"> \r\n");
      out.write("                  \t</form>\r\n");
      out.write("                   \r\n");
      out.write("                    \r\n");
      out.write("                </center>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
